name: build

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Docker Build Test
        run: |
          docker build -t localrunner .