name: Build Docker Image

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Use Temporary Disk as Docker Path
        run: |
          sudo service docker stop
          cd /var/lib
          sudo rm -rf docker
      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c #v10
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          build-mount-path: '/var/lib/docker'
      - name: Restart Docker
        run: |
          sudo service docker start
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.DOCKER_SERVER_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            ${{ secrets.DOCKER_SERVER_URL }}/azterraform:latest